import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { ReduxProvider } from "./redux/provider/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                // colorPrimary: 'rgb(102, 193, 155)',
                colorTextBase: "#0a2d40",
                colorSuccess: "#87df98",
                colorError: "#da1c5c",
                colorInfo: "#633c9c",

                fontFamily: "Geist",
                motionDurationMid: "0.0s",
                motionEaseInOut: "0s",
                colorPrimary: "#9e3164",
              },
              components: {
                Table: {
                  // rowSelectedBg: FIRST_GRADIENT,
                  // rowSelectedHoverBg: SECOND_GRADIENT,
                },
                // Menu: {
                //   itemHoverColor: FIRST_GRADIENT,
                //   itemSelectedBg: FIRST_GRADIENT,
                //   itemSelectedColor: "white",
                //   darkItemBg: "white",
                // },
                // Layout: {
                //   siderBg: "white",
                // },

                Menu: {
                  itemHoverColor: "white",
                  itemColor: "white",
                  itemSelectedBg: "white",
                  itemSelectedColor: "black",
                  iconSize: 18,
                  collapsedIconSize: 18,
                  fontSize: 14,
                },
                Layout: {
                  siderBg: "white",
                  triggerBg: "black",
                  triggerColor: "black",
                },
                Button: {
                  // groupBorderColor: "#9e3164",
                  // colorIt
                },
              },
            }}
          >
            <ReduxProvider>{children}</ReduxProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
